import { Module } from '@nestjs/common';
import { InfrastructureLayerModule } from '../infrastructure/infrastructureLayer.module';
import {
    FilesFactory,
    UserFactory,
    CompanyFactory,
    TaxSettingsFactory,
    LibelleFactory,
    InvoiceFactory,
} from './factoryMapper';
import {
    UserUseCases,
    SuperAdminUseCases,
    FilesUseCases,
    AuthUseCases,
    CompanyUseCases,
    TaxSettingsUseCases,
    LibelleUseCases,
    InvoiceUseCases,
    PurchaseInvoiceUseCases,
    AnalysisUseCases,
    EmployeeUseCases,
    SalaryUseCases,
    CnssPaymentUseCases,
    TvaPaymentUseCases,
} from './useCases';
import { XmlGeneratorService } from './services/xml-generator.service';

@Module({
    imports: [
        InfrastructureLayerModule,
    ],
    providers: [
        UserFactory,
        UserUseCases,
        SuperAdminUseCases,
        AuthUseCases,
        FilesFactory,
        FilesUseCases,
        CompanyFactory,
        CompanyUseCases,
        TaxSettingsFactory,
        TaxSettingsUseCases,
        LibelleFactory,
        LibelleUseCases,
        InvoiceFactory,
        InvoiceUseCases,
        PurchaseInvoiceUseCases,
        AnalysisUseCases,
        EmployeeUseCases,
        SalaryUseCases,
        CnssPaymentUseCases,
        TvaPaymentUseCases,
        XmlGeneratorService,
    ],
    exports: [
        UserFactory,
        UserUseCases,
        SuperAdminUseCases,
        AuthUseCases,
        FilesFactory,
        FilesUseCases,
        CompanyFactory,
        CompanyUseCases,
        TaxSettingsFactory,
        TaxSettingsUseCases,
        LibelleFactory,
        LibelleUseCases,
        InvoiceFactory,
        InvoiceUseCases,
        PurchaseInvoiceUseCases,
        AnalysisUseCases,
        EmployeeUseCases,
        SalaryUseCases,
        CnssPaymentUseCases,
        TvaPaymentUseCases,
        XmlGeneratorService,
    ],
})
export class ApplicationLayerModule { }
